
package Views;


import Models.TypeArticleModel;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;


public class AddNewArticlesView extends javax.swing.JDialog {
    private ArticlesViews artVPerent ;// this varible is declareted to creat a relation between the Article Controller and Add Article Controller to use some methodes from Article Contoller 
    public AddNewArticlesView(ArticlesViews v ,boolean  mod) {
        super (v,mod);
        this.artVPerent = v;
        setUndecorated(true);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFermer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtQua = new javax.swing.JTextField();
        txtPrc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comType = new javax.swing.JComboBox<>();
        btnAddArt = new javax.swing.JButton();
        txtDsg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADD NEW ARTICLES ");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnFermer.setBackground(new java.awt.Color(102, 153, 255));
        btnFermer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFermer.setForeground(new java.awt.Color(255, 255, 255));
        btnFermer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_back_arrow_32px.png"))); // NOI18N
        btnFermer.setFocusable(false);
        btnFermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFermerMouseClicked(evt);
            }
        });
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(btnFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addGap(0, 272, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFermer, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 700, -1));

        jPanel2.setBackground(new java.awt.Color(132, 176, 201));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQua.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(txtQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 296, 46));

        txtPrc.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(txtPrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 296, 48));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ENTER  ARTICLE PRICE ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ENTER ARTICLE  QUANTITY");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ENTER ARTICLE DESIGNATION ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("CHOOSE AN ARTICLE TYPE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        comType.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(comType, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 296, 39));

        btnAddArt.setBackground(new java.awt.Color(102, 255, 102));
        btnAddArt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_32px_1.png"))); // NOI18N
        btnAddArt.setText("ADD");
        btnAddArt.setFocusable(false);
        jPanel2.add(btnAddArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 159, -1));

        txtDsg.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(txtDsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 296, 39));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFermerMouseClicked

    }//GEN-LAST:event_btnFermerMouseClicked

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        
    }//GEN-LAST:event_btnFermerActionPerformed

    

    public void remplireComboItems (ArrayList <TypeArticleModel> a){
        a.forEach(typeArticleModel ->{
           comType.addItem(typeArticleModel.getLibbleTypeArt());
       });  
    }
    public void setActionClose (ActionListener a ){
        btnFermer.addActionListener(a);
    }
    public String  getTxtDsg (){
        return txtDsg.getText();
    }
     public String  getTxtQua (){
        return txtQua.getText();
    }
     public String  getTxtPrc (){
        return txtPrc.getText();
    }
     public int  getComItem (){
        return comType.getSelectedIndex();
    }
    
     public void setActionAdd (ActionListener a ){
         btnAddArt.addActionListener(a);
     }
     
     public ArticlesViews  getPerent (){
        return artVPerent;
    }
     
    public void clearContent (){
        txtDsg.setText("");
        txtQua.setText("");
        txtPrc.setText("");
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArt;
    private javax.swing.JButton btnFermer;
    private javax.swing.JComboBox<String> comType;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDsg;
    private javax.swing.JTextField txtPrc;
    private javax.swing.JTextField txtQua;
    // End of variables declaration//GEN-END:variables

    public void setMouseListnerForHeaderPanel(MouseAdapter mouseAdapter) {
        headerPanel.addMouseListener(mouseAdapter);
    }

    public void setMouseMotionListnerForHeaderPanel(MouseAdapter mouseAdapter) {
      headerPanel.addMouseMotionListener(mouseAdapter);  
    }
}
